### ISSUE TITLE
Pointnet2 cannot be installed

### ISSUE THREAD

**Issue by wangsenchen** [YBZh/MaskSurf#1]
Hello, did you encounter this situation when installing the pointnet2 library?

Cloning https://github.com/erikwijmans/Pointnet2_PyTorch.git to c:\users\xiaomumu\appdata\local\temp\pip-install-5i7vkh4_\pointnet2-ops_1abcf7a21ccb40348dd4ac624101674f
Running command git clone --filter=blob:none --quiet https://github.com/erikwijmans/Pointnet2_PyTorch.git 'C:\Users\xiaomumu\AppData\Local\Temp\pip-install-5i7vkh4_\pointnet2-ops_1abcf7a21ccb4
0348dd4ac624101674f'
fatal: unable to access 'https://github.com/erikwijmans/Pointnet2_PyTorch.git/': Failed to connect to github.com port 443 after 21206 ms: Timed out
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/erikwijmans/Pointnet2_PyTorch.git 'C:\Users\xiaomumu\AppData\Local\Temp\pip-install-5i7vkh4_\pointnet2-ops_1abcf7a21ccb40348dd4ac6241
01674f' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/erikwijmans/Pointnet2_PyTorch.git 'C:\Users\xiaomumu\AppData\Local\Temp\pip-install-5i7vkh4_\pointnet2-ops_1abcf7a21ccb40348dd4ac624101
674f' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by YBZh** [comment]
Sorry, I did not meet such a problem. It seems to be a problem related to the pointnet2 library, maybe you should open the issue under pointnet2.

**Comment by wangsenchen** [comment]
Thank you for your reply
