### ISSUE TITLE
Cannot downlaod the Shapenet dataset with norml.

### ISSUE THREAD

**Issue by HAHAHA-7L7** [YBZh/MaskSurf#4]
The link provided in the DATASET.md seems only contain the ScanObjectNN_hardest_fewshot.tar. How can I get the shapenet with normal? Thanks.

**Comment by YBZh** [comment]
The shapenet dataset is deleted due the limited store space. You can create the required dataset with the code: [https://github.com/YBZh/MaskSurf/blob/main/point2normal_curve.py](url)
